#!/bin/bash

# This script generates a list of random passwords.

# A random number as a password.
 # by RANDOM a random integer between 0 and 32767 is generated.(more details in 'man bash' section 'random')
PASSWORD="${RANDOM}"
echo "${PASSWORD}"

# Three random numbers together.
PASSWORD="${RANDOM}${RANDOM}${RANDOM}"
echo "${PASSWORD}"

# Use the current date/time as the basis for the password.
 # command is used '(date +%s)' - (more details in 'man date' section 'format')
PASSWORD="$(date +%s%N)"
echo "${PASSWORD}"

# A better password.
 # sha256 to hash the password and head to select the 1st 32 char
PASSWORD=$(date +%s%N | sha256sum | head -c 32)
echo "${PASSWORD}"

# An even better password.
PASSWORD=$(date +%s%N${RANDOM}${RANDOM} | sha256sum | head -c48)
echo "${PASSWORD}"

# Append a special character to the even better passsword.
 # fold separactes char to 1 line each char, shuf randomly choose the one char.
SPECIAL_CHAR=$(echo '!@#$%^&*()_+=' | fold -w1 | shuf | head -c1)
echo "${PASSWORD}${SPECIAL_CHAR}"
