#!/bin/bash

# This script generates a random password
# This user can set password lenght with -l and add a special character with -s.
# Verbose mode can be enabled with -v.

usage() {
  echo "Usage: ${0} [-vs] [-l LENGTH]" >&2
  echo 'Generate a random password'
  echo ' -l        LENGTH Specify the password length.'
  echo ' -s        Append a special character to the password.'
  echo ' -v        Increase verbosity.'
  exit 1
}

log(){
 local MESSAGE="${@}"
 if [[ "${VERBOSE}" = 'true' ]]
 then
  echo "${MESSAGE}"
 fi
}


# Set a default password lenght.
LENGTH=24

while getopts vl:s OPTION
do
  case ${OPTION} in
    v)
      VERBOSE='true'
      log 'Verbose mode on.'
      ;;
    l)
      LENGTH="${OPTARG}"
      ;;
    s)
      USE_SPECIAL_CHARACTER='true'
      ;;
    ?)
      usage
      ;;
  esac
done

log 'Generating a password'

PASSWORD="$(date +%N${RANDOM}${RANDOM}${CHAR} | sha256sum | head -c${LENGTH})"

# Append a special character if requested to do so.
if [[ "${USE_SPECIAL_CHARACTER}" = 'true' ]]
then
  log 'Selecting a random special char'
  CHAR="$(echo '!@#%^*' | fold -w1 | shuf | head -c1)"
  PASSWORD="${PASSWORD}${CHAR}"  
fi

echo ${PASSWORD}
